# Generated by Django 4.1.7 on 2025-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(help_text='Duration in weeks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
